#ifndef METHODMESH_GATEWAY_PROTOCOL_H
#define METHODMESH_GATEWAY_PROTOCOL_H

/* Module-owned Android↔gateway bridge constants. ESP-NOW routing is separate. */
#define METHODMESH_GATEWAY_PROTOCOL "methodmesh.gateway"
#define METHODMESH_GATEWAY_VERSION 1
#define METHODMESH_GATEWAY_MAX_FRAME_BYTES 4096

#define METHODMESH_GATEWAY_SERVICE_UUID "b6f2a910-9b8f-4f4e-9a1f-4f37a0010000"
#define METHODMESH_GATEWAY_UPLINK_UUID "b6f2a911-9b8f-4f4e-9a1f-4f37a0010000"
#define METHODMESH_GATEWAY_DOWNLINK_UUID "b6f2a912-9b8f-4f4e-9a1f-4f37a0010000"

/* The firmware implementation must validate these kinds before acting. */
#define METHODMESH_GATEWAY_KIND_HELLO "HELLO"
#define METHODMESH_GATEWAY_KIND_HELLO_ACK "HELLO_ACK"
#define METHODMESH_GATEWAY_KIND_OUTBOUND "OUTBOUND"
#define METHODMESH_GATEWAY_KIND_INBOUND "INBOUND"
#define METHODMESH_GATEWAY_KIND_STATUS "STATUS"

#endif
