#ifndef METHODMESH_GATEWAY_PROTOCOL_H
#define METHODMESH_GATEWAY_PROTOCOL_H

/* Module-owned Android↔gateway bridge constants. ESP-NOW packetisation is separate. */
#define METHODMESH_GATEWAY_PROTOCOL "methodmesh.gateway"
#define METHODMESH_GATEWAY_VERSION 2
#define METHODMESH_GATEWAY_MAX_FRAME_BYTES 65535

#define METHODMESH_GATEWAY_SERVICE_UUID "b6f2a910-9b8f-4f4e-9a1f-4f37a0010000"
#define METHODMESH_GATEWAY_UPLINK_UUID "b6f2a911-9b8f-4f4e-9a1f-4f37a0010000"
#define METHODMESH_GATEWAY_DOWNLINK_UUID "b6f2a912-9b8f-4f4e-9a1f-4f37a0010000"

#define METHODMESH_GATEWAY_KIND_HELLO "HELLO"
#define METHODMESH_GATEWAY_KIND_HELLO_ACK "HELLO_ACK"
#define METHODMESH_GATEWAY_KIND_CONFIG "CONFIG"
#define METHODMESH_GATEWAY_KIND_CONFIG_ACK "CONFIG_ACK"
#define METHODMESH_GATEWAY_KIND_DATA "DATA"
#define METHODMESH_GATEWAY_KIND_LOCAL_STORED "LOCAL_STORED"
#define METHODMESH_GATEWAY_KIND_REMOTE_STORED "REMOTE_STORED"
#define METHODMESH_GATEWAY_KIND_PHONE_STORED "PHONE_STORED"
#define METHODMESH_GATEWAY_KIND_SYNC_REQUEST "SYNC_REQUEST"
#define METHODMESH_GATEWAY_KIND_SYNC_ACK "SYNC_ACK"
#define METHODMESH_GATEWAY_KIND_VOICE_LISTEN "VOICE_LISTEN"
#define METHODMESH_GATEWAY_KIND_VOICE_LISTEN_ACK "VOICE_LISTEN_ACK"
#define METHODMESH_GATEWAY_KIND_LIVE_VOICE "LIVE_VOICE"
#define METHODMESH_GATEWAY_KIND_LIVE_VOICE_RX "LIVE_VOICE_RX"
#define METHODMESH_GATEWAY_KIND_RADIO_ERROR "RADIO_ERROR"
#define METHODMESH_GATEWAY_KIND_ERROR "ERROR"

/* Larger logical frames are transparently packetised as methodmesh.blefrag v1. */
#define METHODMESH_BLE_FRAGMENT_PROTOCOL "methodmesh.blefrag"
#define METHODMESH_BLE_FRAGMENT_VERSION 1

#endif
